version: '2'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - .:/go/src/github.com/sbr35/wallets-users/
    env_file:
      - .env
    ports:
      - 8000:8080
    depends_on:
      - db
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: